import streamlit as st
import pandas as pd
from datetime import datetime
import pytz

# ---------------------------
# 1. ページ設定 & 余計な表示を消すCSS
# ---------------------------
st.set_page_config(page_title="Co-Write Sprinter", page_icon="🦁", layout="centered")

# 右上のメニューや下のフッターを隠す魔法のCSS
hide_streamlit_style = """
            <style>
            #MainMenu {visibility: hidden;}
            footer {visibility: hidden;}
            header {visibility: hidden;}
            /* デッドラインの文字サイズ調整 */
            .big-font {
                font-size:20px !important;
                font-weight: bold;
                color: #FF4B4B;
            }
            </style>
            """
st.markdown(hide_streamlit_style, unsafe_allow_html=True)

# ---------------------------
# 2. ロジック（時間計算）
# ---------------------------
DEADLINE = datetime(2026, 1, 14, 23, 59, 0, tzinfo=pytz.timezone('Asia/Tokyo'))
now = datetime.now(pytz.timezone('Asia/Tokyo'))
diff = DEADLINE - now

# ---------------------------
# 3. メイン画面：デッドライン表示（最優先！）
# ---------------------------
# スマホで一番最初に見るべき情報はこれ！
if diff.total_seconds() > 0:
    days = diff.days
    hours = diff.seconds // 3600
    minutes = (diff.seconds % 3600) // 60
    
    # 視覚的にわかりやすくバーで表示
    progress_val = max(0, min(100, int((1 - diff.total_seconds() / (7*24*60*60)) * 100)))
    
    # 文字で表示（カスタムHTMLでサイズ制御）
    st.markdown(f'<p class="big-font">🔥 DEADLINEまで：あと {hours}時間 {minutes}分</p>', unsafe_allow_html=True)
    st.progress(progress_val)
else:
    st.error("🚨 締め切り過ぎてます！！提出急げ！！")

st.write("---") # 区切り線

# ---------------------------
# 4. タスク管理ボード
# ---------------------------
st.subheader("🚀 制作進行ボード") # タイトルサイズを少し小さく

# タブを作る
tab1, tab2, tab3 = st.tabs(["1. Pose", "2. Masterpiece", "3. Runner"])

def task_list(song_name, task_data):
    st.markdown(f"**🎵 {song_name}**") # 曲タイトルも少し小さく太字で
    
    # 完了数カウント
    done_count = 0
    total_tasks = len(task_data)
    
    for task_name, info in task_data.items():
        # 担当者アイコン
        person_icon = "🦁" if info["person"] == "miyoshi" else "👤"
        label = f"{person_icon} {task_name}"
        
        # チェックボックス
        checked = st.checkbox(label, value=info["done"], key=f"{song_name}_{task_name}")
        if checked:
            done_count += 1
            
    # 進捗率
    if total_tasks > 0:
        progress = done_count / total_tasks
        st.caption(f"進捗: {int(progress * 100)}%")
        st.progress(progress)

# --- 曲ごとのデータ（ここを書き換えればタスクが変わります） ---

# 1曲目
tasks_1 = {
    "ギター本番録音": {"person": "miyoshi", "done": True},
    "サビ構成変更": {"person": "umezawa", "done": True},
    "ミックス最終確認": {"person": "umezawa", "done": False}
}

# 2曲目
tasks_2 = {
    "歌データ送信": {"person": "miyoshi", "done": True},
    "ブラス追加・Mix": {"person": "umezawa", "done": False},
}

# 3曲目
tasks_3 = {
    "アレンジ提出": {"person": "umezawa", "done": False},
    "ボーカルRec": {"person": "miyoshi", "done": False},
    "BPM/Key固定確認": {"person": "miyoshi", "done": True},
}

with tab1:
    task_list("Pose & Gimmick", tasks_1)

with tab2:
    task_list("絶対的マスターピース！", tasks_2)

with tab3:
    task_list("GO! GO! RUNNER!", tasks_3)

st.markdown("---")
st.caption("Auto-generated by Gemini")
